# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: I am Sen
name: Sen
email: seniscz@gmail.com
location: shanghai
company: #
company_url: my_company_website
github_url: https://github.com/seniscz
github_username: seniscz
description: 广交朋友，走向生活
favicon: seniscz.png
repository: github_username/github_username.github.io # ex. DONGChuan/DONGChuan.github.io

# The base hostname & protocol for your site
# For local test, please use http://localhost:4000
# For production, use your github page url. ex. http://dongchuan.github.io
url: http://localhost:4000

## Gem
gems:
  - jekyll-paginate
  - jekyll-geo-pattern
  - rouge
  - kramdown
  - jekyll-github-metadata

# Build settings
markdown: kramdown
highlighter: rouge
lsi:         false
excerpt_separator: "\n\n"

source:      .
destination: ./_site

quiet:    false
defaults: []

kramdown:
  input: GFM
  enable_coderay: true

# Disque
disque: my_disque_settings # ex. httpdongchuangithubio.disqus.com

# Pagination
paginate: 10
paginate_path: 'page:num'

# Navigation. If you do not like these modules, just remove them
# top menu list
menus:

  -
    href: /link.html
    label: 友链
    target: _self

    - href: /life.html
      label: 生活
      target: _self
  -
    href: /about
    label: About

# Navigation. main menu list
navs:

-
  href: /
  label: Home

-
  href: /linux.html
  label: Linux
  target: _self
  subnav:

  -
    subHref: /linux_perf_opt.html
    subLabel: Linux性能优化
  -
    subHref: /shell.html
    subLabel: Shell编程

-
  href: /bigdata.html
  label: Big Data Ecosphere
  target: _self
  subnav:

  -
    subHref: /flink.html
    subLabel: Flink

  - subHref: /kudu.html
    subLabel: KUDU

-

  href: http://www.justdojava.com
  label: Java
  target: _blank
  subnav:

  -
    subHref: /java.html
    subLabel: Jvm 系列文章

  -
    subHref: http://www.justdojava.com
    subLabel: Java 极客技术
    target: _blank

-
  href: /data_structure.html
  label: 数据结构
  target: _self


# labels. my blog key words
labels:

-
  href: /flink.html
  label: Flink
  target: _self

-
  href: /kudu.html
  label: Kudu
  target: _blank

-
  href: /open-source.html
  label: Code
  target: _blank


# selected articles
classes:

-
  href: /life.html
  name: 我的故事
  describe: 生活就是故事，故事就是生活

-
  href: /arch.html
  name: 架构师之路
  describe: 一个架构师的自我修养

-
  href: /java.html
  name: Java 系列文章
  describe: Java 之根基，Java 程序员必学


# ---------------- #
#       RSS        #
# ---------------- #
subscribe_rss: /feed.xml

# Sidebar to show popular repo
side_bar_repo_limit: 6 # Number of repos to show

# Google Analytics
analytics :
  provider : google
  google :
      tracking_id : 'tracking_id'  # ex. UA-72165600-X


# For about.html. Fell free to create your own!
skill_software_keywords: [Java, Scala, MySQL, Kudu, Flink, Design Patterns]
skill_j2ee_keywords: [Spring, Struct, Hibernet, MyBatis, JSP]
skill_web_keywords: [HTML, CSS, JS, JQuery, Ajax, AngularJS, NodeJS, ExpressJS, MongoDB, Redis, PHP, Symfony, Boostrap]
skill_mobile_app_keywords: [Android, Sketch UI Desgin]



# ---------------- #
#      Comments    #
# ---------------- #
# support provider: disqus, gitment, gitalk
comments_provider: gitalk
# !!!重要!!! 请修改下面这些信息为你自己申请的
# !!!Important!!! Please modify infos below to yours
# https://disqus.com
disqus:
  username: ityouknow
# https://imsun.net/posts/gitment-introduction/
gitment:
  owner: ityouknow
  repo: blog-comments
  oauth:
    client_id: 61bfc53d957e74e78f8f
    client_secret: 31c61e66cdcc9ada8db2267ee779d0bdafac434c
# https://github.com/gitalk/gitalk#install
gitalk:
  owner: ityouknow
  repo: blog-comments
  clientID: 61bfc53d957e74e78f8f
  clientSecret: 31c61e66cdcc9ada8db2267ee779d0bdafac434c
# 在使用其它评论组件时可点击显示 Disqus
lazy_load_disqus : true