# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: I am Sen
name: Sen
email: seniscz@gmail.com
location: shanghai
company: VIP
company_url: https://www.peilian.com/?utm_source=bdpz_pc&utm_medium=cpc&utm_campaign=%E7%99%BE%E5%BA%A6%E5%93%81%E4%B8%93&utm_term=%E4%B8%BB%E6%A0%87%E9%A2%98&utm_content=%E5%B7%A6%E4%BE%A7
github_url: https://github.com/seniscz
github_username: seniscz
description: 广交朋友，走向生活
favicon: seniscz.png
encoding: "utf-8"
repository: seniscz/seniscz.github.io  # ex. DONGChuan/DONGChuan.github.io

# The base hostname & protocol for your site
# For local test, please use http://localhost:4000
# For production, use your github page url. ex. http://dongchuan.github.io
#url: http://localhost:4000

## Gem
gems:
  - jekyll-paginate
  - jekyll-geo-pattern
  - rouge
  - kramdown
  - jekyll-github-metadata

# Build settings
markdown: kramdown
highlighter: rouge
lsi:         false
excerpt_separator: "\n\n"

source:      .
destination: ./_site

quiet:    false
defaults: []
  
kramdown:
  input: GFM
  enable_coderay: true

   
# Disque
disque: httpdongchuangithubio.disqus.com # ex. httpdongchuangithubio.disqus.com

# Pagination
paginate: 5
paginate_path: 'page:num'


# Navigation. If you do not like these modules, just remove them
# Navigation. main menu list
navs:
  -
    href: /
    label: Home

  -
    href: /open-source
    label: Open-Source

  -
    href: /blog
    label: Blog

  -
    href: /bookmark
    label: Bookmark

  -
    href: /about
    label: About
  -
    href: /link.html
    label: 友链
    target: _self
 -
    href: /life.html
    label: 生活
    target: _self


# top menu list
menus:

 -
    href: /link.html
    label: 友链
    target: _self
 -
    href: /life.html
    label: 生活
    target: _self

 


# ---------------- #
#       RSS        #
# ---------------- #
# subscribe_rss: /feed.xml

# Sidebar to show popular repo, 侧边显示的是仓库的项目
# side_bar_repo_limit: 0 # Number of repos to show

# Google Analytics
analytics :
  provider : google
  google :
    tracking_id : 'tracking_id'  # ex. UA-72165600-X


# For about.html. Fell free to create your own!
skill_software_keywords: [Java, Scala, MySQL, Kudu, Flink, Design Patterns]
skill_j2ee_keywords: [Spring, Struct, Hibernet, MyBatis, JSP]
skill_web_keywords: [HTML, CSS, JS, JQuery, Ajax, AngularJS, NodeJS, ExpressJS, MongoDB, Redis, PHP, Symfony, Boostrap]
skill_mobile_app_keywords: [Android, Sketch UI Desgin]




